### ISSUE TITLE
Unit tests fail when a loaded module starts with a hashbang (#!)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/testing#10]
https://travis-ci.org/Apollon77/ioBroker.meross/jobs/504243109#L798

local error is

```
1) Test the adapter (in a mocked environment)
       The adapter starts in normal mode:
     /Volumes/Dev/GitHub/ioBroker.meross/node_modules/mqtt/mqtt.js:1
(function (exports, require, module, __filename, __dirname) { ((process) => {#!/usr/bin/env node
                                                                             ^

SyntaxError: Invalid or unexpected token
      at createScript (vm.js:80:10)
      at Object.runInThisContext (vm.js:139:10)
      at Module.module._compile (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:148:24)
      at Object.replaceJsLoader [as .js] (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:152:9)
      at Module.fakeRequire [as require] (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:28:16)
      at require (internal/module.js:11:18)
      at EventEmitter (node_modules/meross-cloud/index.js:8:14)
      at Object.<anonymous> (node_modules/meross-cloud/index.js:363:3)
      at Module.module._compile (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:148:24)
      at Object.replaceJsLoader [as .js] (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:152:9)
      at Module.fakeRequire [as require] (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:28:16)
      at require (internal/module.js:11:18)
      at /Volumes/Dev/GitHub/ioBroker.meross/main.js:13:21
      at Object.<anonymous> (main.js:520:3)
      at Module.module._compile (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:148:24)
      at Object.replaceJsLoader [as .js] (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:152:9)
      at require (internal/module.js:11:18)
      at Object.loadModuleInHarness (node_modules/@iobroker/testing/build/tests/unit/harness/loader.js:158:26)
      at Object.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:54:41)
      at Generator.next (<anonymous>)
      at /Volumes/Dev/GitHub/ioBroker.meross/node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:9:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:5:12)
      at Object.startMockAdapter (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:27:12)
      at Context.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/index.js:43:114)
      at Generator.next (<anonymous>)
      at /Volumes/Dev/GitHub/ioBroker.meross/node_modules/@iobroker/testing/build/tests/unit/index.js:9:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@iobroker/testing/build/tests/unit/index.js:5:12)
      at Context.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/index.js:39:20)
```

**Comment by AlCalzone** [comment]
Fixed in v1.1.6
