### ISSUE TITLE
Unit test for non-compact mode fails if export is done by checking module and require.main

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/testing#363]
Using

```javascript
if (require.main === module) {
    startAdapter();
} else {
    // export for compact mode
    module.exports = startAdapter;
}
```

as start condition fails with the following error:

```
Test the adapter (in a mocked environment)
       The adapter starts in normal mode:
     Error: The adapter was not initialized!
      at Object.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:108:23)
      at Generator.next (<anonymous>)
      at /home/moritz/workspaces/ioBroker.denon/node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:28:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:24:12)
      at Object.startMockAdapter (node_modules/@iobroker/testing/build/tests/unit/harness/startMockAdapter.js:50:12)
      at Context.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/index.js:67:83)
      at Generator.next (<anonymous>)
      at /home/moritz/workspaces/ioBroker.denon/node_modules/@iobroker/testing/build/tests/unit/index.js:10:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@iobroker/testing/build/tests/unit/index.js:6:12)
      at Context.<anonymous> (node_modules/@iobroker/testing/build/tests/unit/index.js:63:20)
```

**Comment by AlCalzone** [comment]
I can reproduce it in a test case but I have no clue how to overwrite the `require.main` property in a way that actually does something.

We should just get rid of the startup unit tests.
