### ISSUE TITLE
no reply to sendTo received since update to 4.x

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/testing#524]
Not sure what is wrong.

The code pretty much looks like in the Readme/example:
https://github.com/ioBroker/ioBroker.lovelace/blob/master/test/integrationTests/testTools.js#L34

Only the code is in a tool library and so on... startAndWait is called before and awaited for. Adapter is running and prints debug messages on console fine, it 'seems' to be sending the message as expected

But I never receive a response in the testing code. 

I see a warning, though:
```
2022-09-01 10:39:35.216  - warn: lovelace.0 (1822001) States system pmessage io.messagebox.system.adapter.lovelace.0 {"command":"browse","message":{"message":"egal :-p"},"from":"system.adapter.test.0","callback":{"message":{"message":"egal :-p"},"id":1,"ack":false,"time":1662021575213},"_id":41037302} Parameter "message" needs to be a real object but type "object" has been passed
2022-09-01 10:39:35.216  - warn: lovelace.0 (1822001) Error: Parameter "message" needs to be a real object but type "object" has been passed
    at Function.assertObject (/tmp/test-iobroker.lovelace/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:215:19)
    at AdapterClass.sendTo (/tmp/test-iobroker.lovelace/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:4920:27)
    at Object.message (/tmp/test-iobroker.lovelace/node_modules/iobroker.lovelace/main.js:68:41)
    at change (/tmp/test-iobroker.lovelace/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8289:47)
    at Immediate._onImmediate (/tmp/test-iobroker.lovelace/node_modules/@iobroker/db-states-redis/build/lib/states/statesInRedisClient.js:270:37)
    at processImmediate (node:internal/timers:466:21)
```

This happens after debug output in onMessage in the adapter, and when the adapter tries to call sendTo in response. I checked the "message" parameter, and it is of type array, at the very least it is an empty array (but I printed it, it contains a few objects in this case)...

**Comment by Garfonso** [comment]
Ok, this was a js-controller issue. Changes in js-controller were overlapping with testing upgrade. Sorry. :-)
If I switch back to 4.0.23 this works again.
